//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TopCore.DataAccess
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class TopEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“TopEntities”部分中的连接字符串初始化新 TopEntities 对象。
        /// </summary>
        public TopEntities() : base("name=TopEntities", "TopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TopEntities 对象。
        /// </summary>
        public TopEntities(string connectionString) : base(connectionString, "TopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TopEntities 对象。
        /// </summary>
        public TopEntities(EntityConnection connection) : base(connection, "TopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User 对象。
        /// </summary>
        /// <param name="u_Guid">U_Guid 属性的初始值。</param>
        /// <param name="u_Name">U_Name 属性的初始值。</param>
        /// <param name="u_Password">U_Password 属性的初始值。</param>
        /// <param name="u_Top_AppKey">U_Top_AppKey 属性的初始值。</param>
        /// <param name="u_Top_AppSecret">U_Top_AppSecret 属性的初始值。</param>
        /// <param name="u_Top_SessionKey">U_Top_SessionKey 属性的初始值。</param>
        /// <param name="u_Top_CallbackData">U_Top_CallbackData 属性的初始值。</param>
        /// <param name="u_LastUpdateTime">U_LastUpdateTime 属性的初始值。</param>
        public static User CreateUser(global::System.Guid u_Guid, global::System.String u_Name, global::System.String u_Password, global::System.String u_Top_AppKey, global::System.String u_Top_AppSecret, global::System.String u_Top_SessionKey, global::System.String u_Top_CallbackData, global::System.DateTime u_LastUpdateTime)
        {
            User user = new User();
            user.U_Guid = u_Guid;
            user.U_Name = u_Name;
            user.U_Password = u_Password;
            user.U_Top_AppKey = u_Top_AppKey;
            user.U_Top_AppSecret = u_Top_AppSecret;
            user.U_Top_SessionKey = u_Top_SessionKey;
            user.U_Top_CallbackData = u_Top_CallbackData;
            user.U_LastUpdateTime = u_LastUpdateTime;
            return user;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid U_Guid
        {
            get
            {
                return _U_Guid;
            }
            set
            {
                if (_U_Guid != value)
                {
                    OnU_GuidChanging(value);
                    ReportPropertyChanging("U_Guid");
                    _U_Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("U_Guid");
                    OnU_GuidChanged();
                }
            }
        }
        private global::System.Guid _U_Guid;
        partial void OnU_GuidChanging(global::System.Guid value);
        partial void OnU_GuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Name
        {
            get
            {
                return _U_Name;
            }
            set
            {
                if (_U_Name != value)
                {
                    OnU_NameChanging(value);
                    ReportPropertyChanging("U_Name");
                    _U_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Name");
                    OnU_NameChanged();
                }
            }
        }
        private global::System.String _U_Name;
        partial void OnU_NameChanging(global::System.String value);
        partial void OnU_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Password
        {
            get
            {
                return _U_Password;
            }
            set
            {
                if (_U_Password != value)
                {
                    OnU_PasswordChanging(value);
                    ReportPropertyChanging("U_Password");
                    _U_Password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Password");
                    OnU_PasswordChanged();
                }
            }
        }
        private global::System.String _U_Password;
        partial void OnU_PasswordChanging(global::System.String value);
        partial void OnU_PasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Top_AppKey
        {
            get
            {
                return _U_Top_AppKey;
            }
            set
            {
                if (_U_Top_AppKey != value)
                {
                    OnU_Top_AppKeyChanging(value);
                    ReportPropertyChanging("U_Top_AppKey");
                    _U_Top_AppKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Top_AppKey");
                    OnU_Top_AppKeyChanged();
                }
            }
        }
        private global::System.String _U_Top_AppKey;
        partial void OnU_Top_AppKeyChanging(global::System.String value);
        partial void OnU_Top_AppKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Top_AppSecret
        {
            get
            {
                return _U_Top_AppSecret;
            }
            set
            {
                if (_U_Top_AppSecret != value)
                {
                    OnU_Top_AppSecretChanging(value);
                    ReportPropertyChanging("U_Top_AppSecret");
                    _U_Top_AppSecret = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Top_AppSecret");
                    OnU_Top_AppSecretChanged();
                }
            }
        }
        private global::System.String _U_Top_AppSecret;
        partial void OnU_Top_AppSecretChanging(global::System.String value);
        partial void OnU_Top_AppSecretChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Top_SessionKey
        {
            get
            {
                return _U_Top_SessionKey;
            }
            set
            {
                if (_U_Top_SessionKey != value)
                {
                    OnU_Top_SessionKeyChanging(value);
                    ReportPropertyChanging("U_Top_SessionKey");
                    _U_Top_SessionKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Top_SessionKey");
                    OnU_Top_SessionKeyChanged();
                }
            }
        }
        private global::System.String _U_Top_SessionKey;
        partial void OnU_Top_SessionKeyChanging(global::System.String value);
        partial void OnU_Top_SessionKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_Top_CallbackData
        {
            get
            {
                return _U_Top_CallbackData;
            }
            set
            {
                if (_U_Top_CallbackData != value)
                {
                    OnU_Top_CallbackDataChanging(value);
                    ReportPropertyChanging("U_Top_CallbackData");
                    _U_Top_CallbackData = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_Top_CallbackData");
                    OnU_Top_CallbackDataChanged();
                }
            }
        }
        private global::System.String _U_Top_CallbackData;
        partial void OnU_Top_CallbackDataChanging(global::System.String value);
        partial void OnU_Top_CallbackDataChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime U_LastUpdateTime
        {
            get
            {
                return _U_LastUpdateTime;
            }
            set
            {
                if (_U_LastUpdateTime != value)
                {
                    OnU_LastUpdateTimeChanging(value);
                    ReportPropertyChanging("U_LastUpdateTime");
                    _U_LastUpdateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("U_LastUpdateTime");
                    OnU_LastUpdateTimeChanged();
                }
            }
        }
        private global::System.DateTime _U_LastUpdateTime;
        partial void OnU_LastUpdateTimeChanging(global::System.DateTime value);
        partial void OnU_LastUpdateTimeChanged();

        #endregion
    
    }

    #endregion
    
}
